[package]
name = "actix-plus-utils"
version = "0.1.0"
authors = ["john01dav <john01dav@gmail.com>"]
edition = "2018"

[dependencies]
actix-plus-error = { path = "../actix-plus-error" }
actix-web = "3.3.2"
unic-ucd-category = "0.9.0"
rand = "0.7.3"